# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Generate Schedule Json file
description: Generate Schedule Json file
author: docker
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  spreadsheet-key:
    description: "Google Spreadsheet key"
    required: true
  default-avatar:
    description: "Default avatar"
    required: true
  avatar-base-url:
    description: "Avatar base url"
    required: true
  output-path:
    description: "Output path"
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
