name: Generate Schedule JSON file
description: Generate OPass schedule JSON from a public Google Spreadsheet.
author: CCIP-App
branding:
  icon: "anchor"
  color: "blue"

inputs:
  spreadsheet-key:
    description: "Google Spreadsheet key"
    required: true
  default-avatar:
    description: "Default avatar"
    required: true
  avatar-base-url:
    description: "Avatar base url"
    required: true
  output-path:
    description: "Output path"
    required: true

runs:
  using: "node24"
  main: "dist/index.js"
